### ISSUE TITLE
Export not working properly for Bar Charts

### ISSUE THREAD

**Issue by dhruvjoshi** [imclem/Highcharts-export-module-asp.net#1]
Hi,

I downloaded the project and tried to use it. I found some issues with exporting.
The export is not working fine for BAR charts for following options(Prints link a column chart.)
1. Png
2. Jpeg
3. Pdf

Works fine for svg image.

**Comment by imclem** [comment]
Hi,

I'm trying to understand what is not working properly, but i'm not familiar with svg files, i'm just using a C# lib to transform SVG to png,jpeg, and pdf.

Svg is ok because there's no transformation for this kind of file just a simple download, and for other there are some...

**Comment by dhruvjoshi** [comment]
Hi,

When a BAR chart is exported, it exports as a column chart for all the options except svg image.
I changed the chart type to 'Bar' in the sample code provided by you. After that exported the data in various formats.

Thanks...

**Comment by imclem** [comment]
I will try to convert BAR chart using one other library, let me just a little time i've some pending works for the moment.

**Comment by dhruvjoshi** [comment]
No problem....
Thanks...

**Comment by hussainms** [comment]
Me have the same issue. Waiting for the response.

**Comment by Tek4** [comment]
Checked this out... the problem is with the SVG library, not imclem's code. Not sure exactly why the library doesn't like the bar charts.

**Comment by imclem** [comment]
Sorry for the waiting time, like tek4 says it's a SVG lib problem. I've not currently the time to check what i can do to solve that ... Maybe next week..

**Comment by Tek4** [comment]
Perhaps dhruvjoshi or hussainms will publish a minimal demo on the web and open an issue on the SVG Rendering Engine project site? The SVG project has been slow, but there has been activity lately. If someone came up with a demo of SVG code that failed maybe they would fix the bug.

http://svg.codeplex.com/

**Comment by OlgaD** [comment]
http://svg.codeplex.com/discussions/262065
http://svg.codeplex.com/workitem/10725
New Svg.dll attached to above

I have downloaded the latest Svg source code and applied changes from above links (great thanks to people who found the solutions). Built new dll, seems to work now with Bar graphs, however did not have time to do a full test.

**Comment by Tek4** [comment]
Thanks OlgaD, I will try your dll. Also, I have completely re-written the export module to provide many improvements and have permission from imclem to upload it here. I will try to get that done. Let me know your interest level and I will expedite, if necessary.

**Comment by OlgaD** [comment]
Hello! 
We would be extremely interested in your improvements for our project!!! 
We will be starting to work on Highcharts export in September, so there is no need to rush on our part. 

Thank you very much. 
Sincerely yours.
Olga

--- On Thu, 8/11/11, Tek4 reply@reply.github.com wrote:

**Comment by imclem** [comment]
Not logged in since a long time, i will commit the project with the new SVG.dll.

I hope tek4 could commit in a few days :P

**Comment by imclem** [comment]
Thanks to Olga D it's working perfectly with the Svg.dll i will commit this evening.

**Comment by Tek4** [comment]
UPDATE: There appears to be a fork of the SVG.dll project in active development here: https://github.com/vvvv/SVG --- let us know if you try it!
