### ISSUE TITLE
iTextSharp's license violation?

### ISSUE THREAD

**Issue by Shamar** [imclem/Highcharts-export-module-asp.net#11]
Hi, AFAIK, this is a derived work of iTextSharp, an AGPLed library. 
The [Affero GPL v3](http://www.gnu.org/licenses/agpl-3.0.html) imposes that all derived works are distributed under the same licence, recursively.

Thus, right now everyone that linked your library without distributing their source code over the internet (at least to their own final users) is violating the [iTextPdf](http://itextpdf.com)'s  corporate copyrights.

I think you should clarify about this legal issue in your license (you might have obtained a transferable linking exception from iTextPdf) and in the wiki. Otherwise you should fix your licence to be compatible with Affero GPL v3.

**Comment by Tek4** [comment]
Shamar,

Thank you for pointing out your concern. The Affero license, which I included, is just complicated enough that I will need to study it at length (again). I'm trying to understand how it applies to non-commercial works and works not distributed on physical medium. Also, whether or not providing a link to the iText source site is satisfactory. I'd be interested to hear your interpretation and references to any of the clauses in the license text. I'd be likely to just pull the object code out of the repository and let users find it and comply with the license for themselves. Not sure what needs to be done yet, if anything. More details from you would be appreciated. Thanks!

**Comment by Shamar** [comment]
The Affero GPL v3 was studied to close the SaaS loophole of the GPL v2. It simply applies recursively to any derived work, directly or indirectly, including in such definition both code linking (at compile time) and code using (at runtime) the covered software (even via reflection or via a service api) recursively.

Some months ago, I talked with a specialized lawyer of such license for my own AGPLed code, but it's not my own interpretation that is relevant to you, just the one of the iTextSharp's copyright holder. You can find more at http://itextpdf.com/terms-of-use/index.php

As for removing the dll itself, it's not enough: unless you get a linking exception from iTextPDF, your code must be distributed under such a licence (and the same applies to all the application using your code). Concretely you should change your Licence.txt file and the Readme.txt.

Indeed that's the system that many open source companies adopt to pay the bills (see db4o, ext.net ext.js and so on). Another license with even stricter control over derived works is RPL, used by NServiceBus and RavenDB (AFAIK).

My suggestion is to take the question quite seriously, by asking iTextPdf how to comply to their license AND by informing your users about the question.

**Comment by Tek4** [comment]
Thanks for bringing this to my attention. I will undertake a study of the issue.

**Comment by imclem** [comment]
Hi Shamar,

Thank you for your information.

We are using an "old" version of iTextSharp (5.1.3) the license included says:

---

This program is free software; you can redistribute it and/or modify it under the terms of the GNU Affero General Public License version 3 as published by the Free Software Foundation with the addition of the following permission added to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY 1T3XT, 1T3XT DISCLAIMS THE WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program; if not, see http://www.gnu.org/licenses or write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA, 02110-1301 USA, or download the license from the following URL:

http://itextpdf.com/terms-of-use/

The interactive user interfaces in modified source and object code versions of this program must display Appropriate Legal Notices, as required under Section 5 of the GNU Affero General Public License.

In accordance with Section 7(b) of the GNU Affero General Public License, you must retain the producer line in every PDF that is created or manipulated using iText.

You can be released from the requirements of the license by purchasing a commercial license. Buying such a license is mandatory as soon as you develop commercial activities involving the iText software without disclosing the source code of your own applications.
These activities include: offering paid services to customers as an ASP, serving PDFs on the fly in a web application, shipping iText with a closed source product.

For more information, please contact iText Software Corp. at this address: sales@itextpdf.com

---

I don't think that we are violating it, it says that we must, in case disclose the code if we use it in commercial activities we haven't bought a license.
We don't use it in commercial activities and we are distributing the source code of the product.

Correct me if I'm wrong but we are compliant with these terms ?

**Comment by Shamar** [comment]
No. You are _not_ distributing the source code to your customer _under AGPLv3_, thus you are violating the license under which you have received iTextSharp. Even if your product _is not_ commercial, with the current license it could be used by commercial projects that would not violate your copyright but the iTextSharp team's one.

The fact that the source code is available under a different license, is not relevant to AGPLv3.

Thus right now, this piece of code violates the iText Software Corp's copyright.

To be compliant with AGPLv3 you and all the free users of this code must either:
- buy a commercial license from iText Software Corp
- distribute the whole application using this export module as AGPLv3, with full downloadable source code.

However, I'm not a lawyer: I could be wrong.

The solution is simple: ask to iText Software Corp at sales@itextpdf.com

**Comment by Tek4** [comment]
@Shamar I think you may have a valid concern, but I need to study it a bit. I'm unclear on your assertion that the export module is commercial? It is free software. Nothing is for sale here.

**Comment by Shamar** [comment]
@Tek4 Yes this module is free software but it's not AGPLv3 licenced. 
And this is a violation of the AGPLv3 (if you received iTextSharp under that license, obviously). 

Moreover the current license of the module **allows** commercial use of the module even for closed source applications. But all people using your module for closed source or commercial application without a commercial license from iText Software Corp, are violating their copyright.

Such people have to either publish their whole application's source code under AGPLv3 or buy a commercial licence. That's it.

You should just fix the license and inform your users about the mistake.

BTW, this issue has been open a year ago. That's a long long time to fix it.

**Comment by Shamar** [comment]
@Tek4 @imclem any news? Did you asked to sales@itextpdf.com?

**Comment by imclem** [comment]
Not yet. Because I'm not sure they are the right people to ask the question. This question must be asked to a lawyer.

I'm still not sure we are violating something. The code is distributed with the MIT license (X11), which as I understood, can be sub-licensed to anything else including GPLv3 or AGPLv3.

by the way I see 3 options right now:
- go from MIT to AGPLv3
- remove itextsharp dependency and use something else
- keep everything as is

For the 1st option, assuming that the code in the repository has been fully written by @Tek4 based on my first work, I will not make the change myself, it's his choice not mine.

The second one looks good I'm thinking about migrating to report.net or something not licensed GPL or AGPL.

For the last one we must ensure that I'm true.

Yes this issue is opened for 1 year but we are not working intensively on this project.

**Comment by Shamar** [comment]
AFAIK (and I asked a lawyer) the simplest option is to go from MIT to AGPLv3. **But** you have to inform your users that this license's change also applies to all previous versions, because you received iTextSharp as AGPLv3 and thus they received your code under AGPLv3.

You could also double-license the export module as MIT and AGPLv3, specifing that, in order to use the module under MIT license, everybody has to buy a commercial license from iTextSharp's authors.  
But again, those that are using or used the export module as MIT (and thus in applications that are not freely available under AGPLv3) without such commercial license from iText Software Corp, are violating their copyright.

Removing iTextSharp dependecy works for future versions, but you should fix the problem for the current (and past?) versions you distributed.

Finally, AFAIK, if you keep everything as is, you expose you and your users to be reported for copyright violation by iText Software Corp.

**Comment by Vleminckx** [comment]
@Tek4 @imclem : At iText we like the fact that you are keen of our software and use it in your Project(s) but I don't understand why you don't just ask us what you should do to be compliant with our AGPL license or if you need a commercial license. (We do have offices in USA and Europe.) Being compliant to AGPL does not depend on the fact if your software is for sale or not. @Shamar did advise you to contact the company that distributes (and develops) the software, if think that is the simplest way to find out.

**Comment by imclem** [comment]
I added a Warning in the readme, we do not use iTextSharp anymore.

**Comment by ajcsoftware** [comment]
What if a commercial application wants to use iTextSharp but it only uses it by running it via the command line.  I mean build iTextSharp into a free open source application that runs from the command line and make this downloadable separately from the commercial app.

Then the closed source commercial app is distributed on its own and can call on the command line to the open source app.  I assume this will mean a commercial license is not needed?
