### ISSUE TITLE
Internet Explorer title and subtitle display issue

### ISSUE THREAD

**Issue by rajgerman** [imclem/Highcharts-export-module-asp.net#13]
In IE (version 9, 8 and 7) when exporting a chart it seems to not display the title and subtitle correctly. They seem to be really squashed up and completely unreadable.

Is this a known issue and is there a fix for it?

**Comment by Tek4** [comment]
If this is a legitimate issue, it is either with Highcharts, or with the SVG library. This project does not undertake any of the rendering, it is only a pipeline between Highcharts and the SVG library. Thus, you should pose your question on the Highcharts web page. If it is an SVG problem then it will be more difficult to resolve as that project has stagnated.
