### ISSUE TITLE
SVG.dll not converting wrapped text

### ISSUE THREAD

**Issue by anup24goswami** [imclem/Highcharts-export-module-asp.net#16]
Hi Team Github,
We are using Highcharts to show our reports in the form of charts.
We are taking the SVG from Highchart directly and converting it into images by using SVG.dll which we downloaded from below URL:
https://github.com/imclem/Highcharts-export-module-asp.net
But in this conversion we are facing few issues:
A.  Whenever we wrapped the text on X-Axis or Y-Axis the same text display on reports properly:

![image](https://f.cloud.github.com/assets/5030470/840128/ed2ff27e-f367-11e2-9478-b9df62a85c4d.png)

When we are taking the SVG of above chart it showing the wrapped text in SVG:

"<g class="highcharts-axis-labels" ><text style="color: rgb(0, 0, 0); line-height: 14px; font-family: arial, helvetica, sans-serif; font-size: 12px; font-weight: bold; cursor: default; fill: #000;" text-anchor="end" transform="rotate(-65 83.75 223)" x="83.75" y="223"><tspan x="83.75">Washington</tspan><tspan x="83.75" dy="14px">Adventist</tspan><tspan x="83.75" dy="14px">Hospital</tspan></text>"

But when we are converting the same SVG to image by using of SVG.dll then in images we are not getting the wrapped text properly. It removed the second row and onwards of the wrapped text:

![image](https://f.cloud.github.com/assets/5030470/840130/fd48b006-f367-11e2-9f1b-6053b6f08588.png)

Note: Due to some restrictions we can’t use the Export Server of Highcharts so please provide any appropriate solution except using of Highchart export server.

**Comment by Tek4** [comment]
SVG.dll is not developed within this project. Conversion problems with SVG.dll CANNOT be addressed here. Post issues with SVG.dll to the SVG project---

The original SVG project, which appears to no longer be active: http://svg.codeplex.com/

FYI-- You may with to check out this SVG project--which is active: https://github.com/vvvv/SVG

The GitHub project code has not been tested here. It looks promising. If anyone does so, please report back!

Thanks!

**Comment by farooqahmadpk** [comment]
when i export graph to png the label on yaxis not vertical it become horizontal.

**Comment by imclem** [comment]
Please try with this version 76cf6a397e763d16774ffa8a72bb572f2b5f7bb9 and let us know if it fixes the problem.

**Comment by subasubramaniam** [comment]
It helped me at right time.Thank you so much.  version "76cf6a3" is working just with 2 line. But wrapped text is getting overlap when it has more than 2 line. Please help.
Web page
![image](https://cloud.githubusercontent.com/assets/9043287/4534695/ac7893b6-4da8-11e4-946d-1146ee386bb6.png)

Exported png
![image](https://cloud.githubusercontent.com/assets/9043287/4534702/c05bcba0-4da8-11e4-9381-39a6689481c6.png)

**Comment by imclem** [comment]
Hi DotnetPaul,

As said lot of times there, we can't unfortunately help you because we're not the developer of the rendering library. You might give a try there https://github.com/vvvv/SVG.
