### ISSUE TITLE
Exporting to image/pdf will not save the icons/images used in the graph

### ISSUE THREAD

**Issue by hussainms** [imclem/Highcharts-export-module-asp.net#2]
We have downloaded the asp.net sample from https://github.com/razormad/Highcharts-export-module-asp.net for exporting highcharts into images/PDF.

But it seems the asp.net application doesn't exporting the icons included in the graph. 
But while testing the the sample available at http://jsfiddle.net/davidpadbury/WjB7T/embedded/result/ or https://github.com/highslide-software/highcharts.com/pull/250 it using PHP as server and exporting graphics / icons used in graph for marking. 

I suspect that it is an issue with the SVG or iTextSharp modules in .net sample. 

Can you please give a fix or update for this?

Regads,
Hussain

**Comment by imclem** [comment]
Like i say on the over issue i've not currently the time, but i will see what i can do next week.

**Comment by hussainms** [comment]
Hi Clem, Thank you for the response and efforts to put implementation like this online and sharing others. 

I am fine and waiting for your updates next week.

**Comment by imclem** [comment]
I have changed the SVG.dll can you retry now and let me know if it works ?

**Comment by hussainms** [comment]
Thank-you, I will get back to you shortly.

**Comment by imclem** [comment]
Three month of waiting feed back, i think i can close this issue.

If someone is having trouble like huissainms, re-open this issue.

**Comment by cael-gomes** [comment]
Please reopen this issue.

I have a chart (type=scatter), and I am using images to markers

marker: {
                            symbol: 'url(logo.png)'
},

when I export to PDF (or any other option), the chart is empty.
