### ISSUE TITLE
HighStock with overlapped labels

### ISSUE THREAD

**Issue by quim831** [imclem/Highcharts-export-module-asp.net#20]
Hi

When exporting HighStock Chart i get top labels overlapped.
I'm sending a screen shot from the exported file.
![highstock export](https://f.cloud.github.com/assets/6391220/1902659/e0509dd2-7c75-11e3-9cc1-2140549865d1.png)

**Comment by Tek4** [comment]
See #10, #1, and others. Not an export module issue. SVG.dll issue.
