### ISSUE TITLE
Gradient legend is not exported as it is when exporting hihmaps.

### ISSUE THREAD

**Issue by eyas2n** [imclem/Highcharts-export-module-asp.net#22]
Library works nice on normal types of legends but when exporting charts with gradient legends it gives a way different result.
Export result with library:
http://s18.postimg.org/focc2voy1/image.png

Export result with export.highcahrts.com:
http://s11.postimg.org/ar9dcywdf/image.png

**Comment by Tek4** [comment]
Rendering problems lie with the SVG library component, not this project.
Sorry. A better SVG component would be welcomed.

**Comment by imclem** [comment]
Hi,
Can you try with this one please:
https://github.com/imclem/Highcharts-export-module-asp.net/tree/newSVGLib

**Comment by eyas2n** [comment]
@imclem . Tried It. Still the same isse.

**Comment by imclem** [comment]
Unfortunately, it's linked to SVG.dll not the exporting stuff. We can't do anything for you.

We're using (https://github.com/vvvv/SVG) you may try to ask help there.
