### ISSUE TITLE
Testing HighStock 2.0.1

### ISSUE THREAD

**Issue by quim831** [imclem/Highcharts-export-module-asp.net#23]
Hi

This is what I got when exporting to PNG, or any other format.
I'm using HighStock 2.0.1.

![export_highstock](https://cloud.githubusercontent.com/assets/6391220/2892885/5ddb4c46-d542-11e3-8466-c68d1f350ca3.png)

Regards

**Comment by imclem** [comment]
Hi,

I've never tried HighStock, but maybe it's a problem related to the svg lib, can you try with this version please:
https://github.com/imclem/Highcharts-export-module-asp.net/tree/newSVGLib

**Comment by rsalayo** [comment]
Same problem here... Tried the newSVGLib branch but same problem.

**Comment by Netrumble** [comment]
I have the same issue exporting HighChart -  line chart. 
I use Version 4.0.1

!!!!!!!!!!!!!!!!!!!! 
I have found this Message in the DebugView:
[6420] w3wp.exe Warning: 0 : 
[6420] Attribute 'opacity' cannot be set - type 'System.Single' cannot convert from string 'undefined'. 
!!!!!!!!!!!!!!!!!!!
This is the export Result:
![exportlinehighchartv4 0 1](https://cloud.githubusercontent.com/assets/1201655/2994580/df94fb12-dccf-11e3-823c-2057852b6f5a.png)

Help Me! it's Urgent for me to fix this bug!

**Comment by imclem** [comment]
We're not writing the rendering library just using the one from (https://github.com/vvvv/SVG) for help with rendering problems, you must ask there.
