### ISSUE TITLE
Exporting Issue HighCharts Line CHart with Export server for ASP.NET

### ISSUE THREAD

**Issue by Netrumble** [imclem/Highcharts-export-module-asp.net#24]
I have a fake  image exporting HighChart -  line chart with Export server for ASP.NET
I use Version 4.0.1

!!!!!!!!!!!!!!!!!!!! 
I have found this Message in the DebugView:
[6420] w3wp.exe Warning: 0 : 
[6420] Attribute 'opacity' cannot be set - type 'System.Single' cannot convert from string 'undefined'. 
!!!!!!!!!!!!!!!!!!!
This is the export Result:
![exportlinehighchartv4 0 1](https://cloud.githubusercontent.com/assets/1201655/2994580/df94fb12-dccf-11e3-823c-2057852b6f5a.png)

Help Me! it's Urgent for me to fix this bug!

**Comment by imclem** [comment]
Hi,

Unfortunately, we can't do so much for you. It looks like a rendering problem and we're not the one who wrote the rendering library. Maybe you can't try to get help here:
https://github.com/vvvv/SVG/tree/master/Samples

**Comment by MohammadKani** [comment]
Hi,

i have same problem, would you help us to solve our problem? i'm using svg.dll

**Comment by kulwinderatt** [comment]
Hi Netrumble,

Did you try solution provided by imclem? I am also facing dame export issue.

Thanks,

**Comment by benrhere** [comment]
I'm also seeing this...

**Comment by kalyangriet** [comment]
Hi

I have the same issue with Line charts, Do you have any updates on the issue?

Please help.

Thanks
Kalyan

**Comment by kulwinderatt** [comment]
My question here is that why we are using this option as ItextSharp is not free.

**Comment by kulwinderatt** [comment]
Hi @imclem,

We tried phantomjs by passing svg but output is not good and it same output provided by @Netrumble  in case of line chart.

**Comment by kalyangriet** [comment]
Hi All

I am not sure if any of you got the answer but I thought to share my approach which fixed it.

I converted the SVG string in to an XML Document and removed the nodes that got created with stroke value as "rgba(192,192,192,0.002)"

Thanks
Kalyan

**Comment by Tek4** [comment]
Care to expound or share your code? Thank you for your effort!

**Comment by kalyangriet** [comment]
Sure.

Step 1: Collect HighChart's SVG in to a hiddenfield on click of my export button using chart.getSVG(). In my case, i had multiple charts on screen.. so i have gathered all charts SVG's using a separator.

if(objType == 'excel' || objType == 'pdf')
{
                var objHdnSVG = document.getElementById('<%=hdnSVG.ClientID %>');
                objHdnSVG.value = '';

```
            var allHighCharts = Highcharts.charts;
            var chartCntr = allHighCharts.length;
            for(var chartCnt = 0; chartCnt < chartCntr; chartCnt++)
            {
                var chart = allHighCharts[chartCnt];
                if(chart != undefined)
                {
                    if(objHdnSVG.value == '')
                        objHdnSVG.value = chart.getSVG();
                    else
                    {
                        objHdnSVG.value = objHdnSVG.value + '|' + chart.getSVG();
                    }
                }
            }
```

}

Step 2: In my Export event in code behind, I am calling my private method "ConvertSVGtoImages()" which splits the SVGs and process each of them:

void excelExport()
{
        ConvertSVGtoImages();
}

Step 3: Here is the ConvertSVGtoImages() method:

private void ConvertSVGtoImages()
{
        uniqueStr = Guid.NewGuid().ToString("N");  
        string[] strSVG = hdnSVG.Value.Split('|');
        int width = 1000;
        int cntr = 0;

```
    for(int svgNbr = 0; svgNbr< strSVG.Length; svgNbr++)
    {            
        string eachSVG = strSVG[svgNbr];
        XmlDocument xmlDoc = new XmlDocument();
        xmlDoc.LoadXml(eachSVG);
        XmlDocument xmlDoc = new XmlDocument();
        xmlDoc.LoadXml(eachSVG);

        foreach (XmlNode xmlnode in xmlDoc.ChildNodes[0].ChildNodes)
        {
                //To remove the unwanted thick stroke from Line chart - start
                if (xmlnode.Attributes["class"] != null && xmlnode.Attributes["class"].Value == "highcharts-series-group")
                {                        
                    foreach (XmlNode childNode in xmlnode.ChildNodes)
                    {
                        if (childNode.Attributes["class"] != null && childNode.Attributes["class"].Value == "highcharts-series")
                        {
                            foreach (XmlNode strokedNode in childNode.ChildNodes)
                            {
                                if (strokedNode.Attributes["stroke"] != null && strokedNode.Attributes["stroke"].Value == "rgba(192,192,192,0.002)")
                                {
                                    childNode.RemoveChild(strokedNode);
                                }
                            }

                        }
                    }
                }
                //To remove the unwanted thick stroke from Line chart - end
            }
            eachSVG = xmlDoc.InnerXml;
            xmlDoc = null;
```

CreateSvgDocument(eachSVG, width).Draw().Save(Server.MapPath(@"\ChartImages\chart_" + uniqueStr + cntr + ".png"));
            cntr++;
}

Last Step: CreateSVGDocuments method:

private SvgDocument CreateSvgDocument(string svg, int width)
    {
        SvgDocument svgDoc;

```
    // Create a MemoryStream from SVG string.
    using (MemoryStream streamSvg = new MemoryStream(
      Encoding.UTF8.GetBytes(svg)))
    {
        // Create and return SvgDocument from stream.
        svgDoc = SvgDocument.Open(streamSvg);
    }

    // Scale SVG document to requested width.
    svgDoc.Transforms = new SvgTransformCollection();
    float scalar = 1; //(float)width / (float)svgDoc.Width;
    svgDoc.Transforms.Add(new SvgScale(scalar, scalar));
    svgDoc.Width = new SvgUnit(svgDoc.Width.Type, svgDoc.Width * scalar);
    svgDoc.Height = new SvgUnit(svgDoc.Height.Type, svgDoc.Height * scalar);
    return svgDoc;
}
```

Hope this helps. Let me know in case of any questions.

Thanks
Kalyan

**Comment by quim831** [comment]
Thanks kalyangriet, very clever code, it's working now.

**Comment by dreymen** [comment]
Using Highcharts 4.0.3 (was using 4.0.1 before) solved this for me....

**Comment by Netrumble** [comment]
Using Highcharts 4.0.3 Fix Issue
