### ISSUE TITLE
Subtitle rendering tiny text

### ISSUE THREAD

**Issue by mhoward90** [imclem/Highcharts-export-module-asp.net#25]
![chartcadvcd1u](https://cloud.githubusercontent.com/assets/8189580/3610851/90e36bcc-0d92-11e4-9fc1-2d897adfec29.png)

If you look closely you can see the sub title, but just rendered in the tiniest font. I had this issue with the legend, but was fixed by upgrading the SVG.dll. Any ideas?

**Comment by imclem** [comment]
The software provided here is not doing the rendering, the rendering is done by a SVG library. You can check with last commit on this branch 76cf6a397e763d16774ffa8a72bb572f2b5f7bb9 (which have a brand new SVG library).

**Comment by birko** [comment]
I am sorry for commenting into this closed issue. but I have the same problem. tried the branch  you suggested but the problem still occurs.  it is a issue when exporting into .png or jpg

**Comment by Tek4** [comment]
birko-- "The software provided here is not doing the rendering, the rendering is done by a SVG library." Rendering issues should be directed at the SVG library, not here. A bug-free SVG library is desired, but has not yet been found.

**Comment by jkriDK** [comment]
I also have issue related to this software. As you maybe know it is possible to add your own text to the charts like shown in the following 
http://jsfiddle.net/8y3d9rua/2/

**Comment by jkriDK** [comment]
Hi. I also have issue related to this software. As you maybe know it is possible to add your own text to a chart like shown in the following jsfiddle
http://jsfiddle.net/8y3d9rua/2/

**Comment by jkriDK** [comment]
Hi! I also have an issue related to "Highcharts-export-module-asp.net". As you maybe know it is possible to add your own text (renderer feature) to a chart like shown in the following jsfiddle:

http://jsfiddle.net/8y3d9rua/2/

and described here:

Docs:
- http://api.highcharts.com/highcharts#Renderer.text
- http://api.highcharts.com/highcharts#chart.events.load

Unfortunately the renderer text is not shown when downloading  "pdf", "jpeg" or PDF file? The renderer text is included when printing or when downloading in svg format. So those two options are working. Any ideas for how to get the renderer text included also in pdf, jpeg or PDF files?

**Comment by jkriDK** [comment]
I have moved the above finding to a new issue:
https://github.com/imclem/Highcharts-export-module-asp.net/issues/30
