### ISSUE TITLE
Export ignoring label rotation

### ISSUE THREAD

**Issue by walteralvarado** [imclem/Highcharts-export-module-asp.net#26]
If I set label rotation in the xAxis, the export ignores this setting. Say I set in my chart options

xAxis: { labels: { rotation: 90 } }

Then the chart displays the X labels vertically, but the export show them horizontally.

**Comment by imclem** [comment]
Probably linked to SVG.dll can you try with latest version on master (I've just merged the one with the new SVG.dll)

**Comment by imclem** [comment]
If the issue is still present try to ask there (https://github.com/vvvv/SVG)
