### ISSUE TITLE
Exported files corrupted

### ISSUE THREAD

**Issue by nixa333** [imclem/Highcharts-export-module-asp.net#27]
I can't really be sure which version, but one of the latest HighCharts updates seems to break the export function, although I also cannot be sure that the HighCharts itself is to blame. What happens is that now, after I've upgraded HighCharts couple of times, I noticed that files being exported are corrupted and cannot be opened. Being that jpg, png, svg or pdf, every one of those files ends up being corrupted and unable to be opened. Do you have any clue why that could be? Only thing that changed is the version of HighCharts lib.

**Comment by imclem** [comment]
Unfortunately no, I haven't any clue on that... Did you tried HighCharts forums ? http://forum.highcharts.com/

**Comment by HaakonSonsteby** [comment]
Any progress? Did you post on the forums? I have the same problem..

**Comment by nixa333** [comment]
Nope, sorry, haven't had time. I replaced it with client-side export for now, until this problem is solved. This is what I'm using http://www.highcharts.com/plugin-registry/single/37/highcharts-export-clientside
