### ISSUE TITLE
Using with MVC

### ISSUE THREAD

**Issue by vahndi** [imclem/Highcharts-export-module-asp.net#28]
Hi, I am trying to use this with an MVC website and DotNetHighcharts, but when I try to download a picture, it gives me a 404 error. I think this is because MVC is prepending the current path to HighchartsExport.axd. Any idea how I fix this? I am creating the Exporting URL for in DotNet, not in javascript.

Requested URL: http://localhost:50377/xxx/yyy/HighchartsExport.axd

**Comment by imclem** [comment]
Hi,

I've never been working with .NET MVC so I'm not of any help here. The pluging hasn't been tested with MVC...

It looks like an integration issue to me, so you might take a look at some .NET MVC forums they can be of more help than I do.

I'm closing this assuming there's no problem with the plugin itself, if there is feel free to reopen. I would appreciate that you post the answer if you find one for other .NET MVC users...

Thanks!
