### ISSUE TITLE
Can this be used to save charts to server drive?

### ISSUE THREAD

**Issue by JohnMcAvinue** [imclem/Highcharts-export-module-asp.net#29]
Hi,

I need to be able to generate images of the charts displayed on a page and add them to a PDF report. I'm trying to find a way of doing this within a server side C# method.

Could this library be used to do it I wonder?

Thanks
John

**Comment by imclem** [comment]
This is actually, what this "Library" does for PDF output, it generates a Bitmap representation of the chart and add it to a PDF document.

Take a look at [Exporter.cs](https://github.com/imclem/Highcharts-export-module-asp.net/blob/master/Tek4.Highcharts.Exporting/Exporter.cs#L226)

**Comment by JohnMcAvinue** [comment]
Thanks very much!
