### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by bsarsgard** [imclem/Highcharts-export-module-asp.net#3]
Hello, I'd like to use this code in a project, but I can't find any licensing information.  Is permission granted to reuse and modify this code?

**Comment by Tek4** [comment]
Yes. Please e-mail me directly as I'd like to hear more about your specific application and will share my experiences.

Kevin
kevin@tek4.com

**Comment by imclem** [comment]
Hi,

As Tek4 said, there's not license so you can use and modify the code. But please if there's something who could be useful for the community share it !
