### ISSUE TITLE
subtitle does not export correctly

### ISSUE THREAD

**Issue by gitchari** [imclem/Highcharts-export-module-asp.net#31]
my chart has title, subtitle, etc. this asp.net highcharts exporter does not export subtitle correctly. I see only a faint dotted line where subtitle should appear.

**Comment by imclem** [comment]
HI!

As said in a number of issues, this is a rendering problem and we're not developing the rendering library. @Tek4 is working on a new version with the latest release of SVG.dll. You might consider waiting for the release and see if it fixes the problem.
