### ISSUE TITLE
Needs to render in browser first, right?

### ISSUE THREAD

**Issue by MaxHorstmann** [imclem/Highcharts-export-module-asp.net#32]
Looks like this first renders the chart in a browser and then sends the svg string back to the server for export - correct?

Any idea how to do this completely server-side?

**Comment by Tek4** [comment]
Right. Highcharts runs on the client browser. To do things server-side, you'd have to run Highcharts on the server. I'm sure plenty of products exist for server-side charting. And, perhaps, there is info about doing so with Highcharts on the Highcharts site. However, a huge feature of Highcharts is user interactivity. You'd lose that going server-side.
