### ISSUE TITLE
Export not working properly for column chart.

### ISSUE THREAD

**Issue by manishavalon** [imclem/Highcharts-export-module-asp.net#4]
Hello, 
I am using your export module with highcharts library. It really provides nice features,  but we are facing some problems.
1. In Firefox, we do not get proper images for column and line charts.Column chart image does not contain bars.In case of Line chart if series data is set multiple times, then exported image contains items based on series data set for the first time.
2. In IE and Chrome, Not getting proper image for all charts. All textual information like Axis Labels, Titles, Legend Items name are missing in image.
This is very serious & important issue for our project. Waiting for your early response.
Thanks & Regards,
Manish

**Comment by Tek4** [comment]
These are probably issues with the SVG rendering engine, which is a separate project. Are you using the latest code? The SVG engine was updated late last year. It doesn't appear the SVG project is very active so I don't have strong hope that any issues will be corrected. Perhaps you might open an issue on that project.

**Comment by Tek4** [comment]
SVG Rendering Engine project page: http://svg.codeplex.com/

**Comment by Tek4** [comment]
UPDATE: There appears to be a fork of the SVG.dll project in active development here: https://github.com/vvvv/SVG --- let us know if you try it!
