### ISSUE TITLE
Upgrade to ASP.NET MVC 3.0

### ISSUE THREAD

**Issue by AMassani** [imclem/Highcharts-export-module-asp.net#5]
Are you planning to release the code for ASP.NET MVC 3.0 soon?

**Comment by Tek4** [comment]
For the export module? I never planned any MVC version of the export module. What exactly are you hoping for?

**Comment by andyscott12** [comment]
Yeah I would be great to see this given the wide adoption of MVC ? Maybe just structure like `controller`, `view` and `model` using Razor template's ?

**Comment by Tek4** [comment]
If you can elucidate some MVC aspect that is pertinent I will consider it.

Honestly, I don't believe MVC is relevant whatsoever. The code provides an HttpHandler which operates in the ASP.NET pipeline below the level where MVC even enters the picture. You use the HttpHandler via configuration within your web.config file and it is not affected in the slightest by MVC routes, etc.

See:
http://forums.asp.net/t/1320309.aspx/1
http://stackoverflow.com/questions/7109344/how-to-call-a-httphandler-in-mvc-asp-net

I don't see any applicability for MVC here. Please provide a specific request if I am wrong. I will leave this issue open for now to allow for additional input/corrections to my position.

**Comment by lamarant** [comment]
I believe AMassani would like to see a demo project that implements this within the .Net MVC framework. I plan on implementing this within my MVC project as well. An MVC demo would be useful.
