### ISSUE TITLE
A generic error occurred in GDI+ exporting png on IIS7.0

### ISSUE THREAD

**Issue by gmaggiodev** [imclem/Highcharts-export-module-asp.net#6]
Exporting to png generate an error:

[ExternalException (0x80004005): A generic error occurred in GDI+.]
   System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams) +378002
   System.Drawing.Image.Save(Stream stream, ImageFormat format) +36
   Tek4.Highcharts.Exporting.Exporter.WriteToStream(Stream outputStream) +234
   Tek4.Highcharts.Exporting.Exporter.WriteToHttpResponse(HttpResponse httpResponse) +67
   Tek4.Highcharts.Exporting.ExportChart.ProcessExportRequest(HttpContext context) +305
   Tek4.Highcharts.Exporting.HttpHandler.ProcessRequest(HttpContext context) +7
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +181
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

I found that the problem is known and a solution is to use a MemoryStream prior to write to response.
This is my code to solve the issue:

```
internal void WriteToHttpResponse(HttpResponse httpResponse)
{
  httpResponse.ClearContent();
  httpResponse.ClearHeaders();
  httpResponse.ContentType = this.ContentType;
  httpResponse.AddHeader("Content-Disposition", this.ContentDisposition);

  if (this.ContentType == "image/png")
  {
      // for png we need to use a memory stream
      using (MemoryStream ms = new MemoryStream())
      {
          WriteToStream(ms);
          ms.WriteTo(httpResponse.OutputStream);
      }
  }
  else
  {
      WriteToStream(httpResponse.OutputStream);
  }
```

**Comment by Tek4** [comment]
Nice work. Could you provide a link to where this is discussed as a known issue? I'd like to read more.

**Comment by gmaggiodev** [comment]
Sure. I found this: 
http://stackoverflow.com/questions/5629251/c-sharp-outputting-image-to-response-output-stream-giving-gdi-error

**Comment by gmaggiodev** [comment]
And also this:
http://www.west-wind.com/weblog/posts/2006/Oct/19/Common-Problems-with-rendering-Bitmaps-into-ASPNET-OutputStream

**Comment by Tek4** [comment]
Gianluca,

Thank you for providing that good information! It appears this only affects PNG images, though a couple remarks indicate this _might_ affect other image types. Does JPEG work for you?

I appreciate your sample code. Your test for "image/png" duplicates the existing switch/case test in the WriteToStream() method, thus I believe I will work your fix into WriteToStream() directly. Something like this maybe?

```
case "image/png":
    // PNG output requires a seekable stream
    using (MemoryStream seekableStream = new MemoryStream())
    {
        CreateSvgDocument().Draw().Save(
            seekableStream,
            ImageFormat.Png);
        seekableStream.WriteTo(outputStream);
    }
    break;
```

I am not at my development machine, thus I will try this out later and upload it. Let me know if you see any errors in the above.

Thanks for your contribution!

**Comment by gmaggiodev** [comment]
I have no problem with jpg.
I also prefer the code inside WriteToStream as you wrote.

Thanks for uploading so quickly.

**Comment by Tek4** [comment]
Not uploaded yet. That is only draft code scratched out in Notepad. I will attempt to get it done late tonight.

Thanks for the feedback on JPEG images.
