### ISSUE TITLE
Exporting does not respect xAxis / yAxis > label > step property for values greater than 1

### ISSUE THREAD

**Issue by gychoy** [imclem/Highcharts-export-module-asp.net#7]
The exporting module does not respect "step" property stated in the document: http://www.highcharts.com/ref/#yAxis-labels

The exported chart's axis contains all of the labels as if step is 1.  And I can't find anywhere in the source code that controls this.  Is it in the SVG engine?

Thanks.

**Comment by Tek4** [comment]
gychoy,

The ProcessExportRequest() method in the ExportChart class receives the HTTP form POST variables from Highcharts. The SVG variable contains the SVG data that represents the chart. This SVG data is passed on--untouched--to the SVG engine (svg.dll).

Hence, there is nothing in the code that alters the appearance of the chart.

If there is an appearance issue, then it is either: (1) Highcharts is exporting incorrect SVG; or, (2) There is an issue with the SVG engine (which is a separate project from this export module).

In your case, I would investigate the raw SVG code to see if the step values appear properly. This may be a Highcharts issue.

**Comment by gychoy** [comment]
Thanks, I'll check it out.

I tested this with "http://export.highcharts.com" by flipping the url and they seem to handle the scenario.  I think they may have modified the svg code further before rendering.

**Comment by Tek4** [comment]
That URL uses a different SVG engine. I'd like to hear further on what you find. It would be nice if the SVG engine project was more active, and fixing bugs.

**Comment by Tek4** [comment]
Appears to be an issue with SVG Rendering Engine (svg.dll) which is a third-party project at http://svg.codeplex.com/

Hopefully there will be renewed interest in that project to fix bugs!
