### ISSUE TITLE
Issue with SvgDocument.Open(streamSvg) method

### ISSUE THREAD

**Issue by AnujPratapSingh** [imclem/Highcharts-export-module-asp.net#8]
Hi,

I am using .NET 2.0 and convert your module to 2.0.
And then try to export chart but SvgDocument.Open(streamSvg) method always returns null.

MemoryStream Read the string, but when i debug the code it's show error but not throw.

((System.IO.Stream)(streamSvg)).ReadTimeout' threw an exception of type 'System.InvalidOperationException'
((System.IO.Stream)(streamSvg)).WriteTimeout' threw an exception of type 'System.InvalidOperationException'

I am unable to find out the issue.
Please help.

Regards
Anuj

**Comment by Tek4** [comment]
Presently, the third-party SVG Rendering Engine (Svg.dll) component is compiled against and requires .NET 3.5.

The SVG Rendering Engine (Svg.dll) project is not well-maintained and is located here:
http://svg.codeplex.com/

The Svg.dll project has several bugs that have been the cause of errors in rendered charts. A fix for one such bug was provided by OlgaD in her comment here:
https://github.com/imclem/Highcharts-export-module-asp.net/issues/1#issuecomment-1783059

OlgaD's fix is the current Svg.dll used in this project, and her fix was compiled against .NET 3.5.

To use the export module with .NET 2.0 would require a version of Svg.dll that does not require .NET 3.5. If this is a must for you, then you will need to look at the changes to Svg.dll made and compiled by OlgaD and see if you can compile Svg.dll against .NET 2.0. Alternatively, you may want to contact OlgaD to see if she can provide her source or provide a .NET 2.0 version.

If the .NET 3.5 dependency is removed from Svg.dll then the export module should work with .NET 2.0.

If you successfully obtain/create a .NET 2.0 version of Svg.dll that includes the fixes made by OlgaD, then please provide it and I will update the export module project.
