### ISSUE TITLE
Not Functioning in IE9

### ISSUE THREAD

**Issue by mpotratz** [imclem/Highcharts-export-module-asp.net#9]
Afternoon,

Downloaded your project, unzipped into a working folder and opened the solution in Visual Studio 10.  Set the Default.aspx as the startup page.  Hit run.

It opens up IE (version 9) for me and then I get this debug error in Visual Studio:

Microsoft JScript runtime error: Object doesn't support property or method 'join' and it opens the Highcharts.js file and highlights the portion of the code  [ "this.d=d.join(" "); ].  Since the code is minimized it's hard to tell exactly where this is happening, but appears to be someplace in the rendering portion of the code.

This only happens in IE, The page works fine in Chrome and Firefox.  Don't have Safari or Opera so can't vouch for them.

Any thoughts or suggestions would be helpful in getting this running.

Mike

**Comment by Tek4** [comment]
Hi Mike! The scope of this project is development of an ASP.NET image export module for use with Highcharts. Highcharts itself (Highcharts.js) is developed by http://www.highcharts.com/ -- I suggest you try one or more of their demos to see if you experience the same issue. If so, you should report the issue on their web site.

My demo project obtains Highcharts.js directly from a URL on their web site. Highcharts.js is not distributed with this project. Hence, it sounds like you may have an issue that they would be interested in examining. They do offer a support forum on their web site.

Kevin
